# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/pz_7z030_axieth_axi_ethernet_3_0.xci
# IP: The module: 'pz_7z030_axieth_axi_ethernet_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/bd_1fd7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7 || ORIG_REF_NAME==bd_1fd7} -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_0/bd_1fd7_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7_eth_buf_0 || ORIG_REF_NAME==bd_1fd7_eth_buf_0} -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_1/bd_1fd7_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7_mac_0 || ORIG_REF_NAME==bd_1fd7_mac_0} -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_2/bd_1fd7_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7_c_shift_ram_0_0 || ORIG_REF_NAME==bd_1fd7_c_shift_ram_0_0} -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_3/bd_1fd7_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7_c_counter_binary_0_0 || ORIG_REF_NAME==bd_1fd7_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_4/bd_1fd7_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7_xlconstant_0_0 || ORIG_REF_NAME==bd_1fd7_xlconstant_0_0} -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_5/bd_1fd7_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7_util_vector_logic_0_0 || ORIG_REF_NAME==bd_1fd7_util_vector_logic_0_0} -quiet] -quiet

# XDC: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/bd_1fd7_ooc.xdc

# XDC: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/pz_7z030_axieth_axi_ethernet_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_7z030_axieth_axi_ethernet_3_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/synth/pz_7z030_axieth_axi_ethernet_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_7z030_axieth_axi_ethernet_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/pz_7z030_axieth_axi_ethernet_3_0.xci
# IP: The module: 'pz_7z030_axieth_axi_ethernet_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/bd_1fd7.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7 || ORIG_REF_NAME==bd_1fd7} -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_0/bd_1fd7_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7_eth_buf_0 || ORIG_REF_NAME==bd_1fd7_eth_buf_0} -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_1/bd_1fd7_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7_mac_0 || ORIG_REF_NAME==bd_1fd7_mac_0} -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_2/bd_1fd7_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7_c_shift_ram_0_0 || ORIG_REF_NAME==bd_1fd7_c_shift_ram_0_0} -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_3/bd_1fd7_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7_c_counter_binary_0_0 || ORIG_REF_NAME==bd_1fd7_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_4/bd_1fd7_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7_xlconstant_0_0 || ORIG_REF_NAME==bd_1fd7_xlconstant_0_0} -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_5/bd_1fd7_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1fd7_util_vector_logic_0_0 || ORIG_REF_NAME==bd_1fd7_util_vector_logic_0_0} -quiet] -quiet

# XDC: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/bd_1fd7_ooc.xdc

# XDC: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/pz_7z030_axieth_axi_ethernet_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_7z030_axieth_axi_ethernet_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/synth/pz_7z030_axieth_axi_ethernet_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_7z030_axieth_axi_ethernet_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
