# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_8/pz_7z030_axieth_auto_cc_8.xci
# IP: The module: 'pz_7z030_axieth_auto_cc_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_8/pz_7z030_axieth_auto_cc_8_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_7z030_axieth_auto_cc_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_8/pz_7z030_axieth_auto_cc_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_7z030_axieth_auto_cc_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_8/pz_7z030_axieth_auto_cc_8.xci
# IP: The module: 'pz_7z030_axieth_auto_cc_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_8/pz_7z030_axieth_auto_cc_8_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_7z030_axieth_auto_cc_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_8/pz_7z030_axieth_auto_cc_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pz_7z030_axieth_auto_cc_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
