webtalk_init -webtalk_dir /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-07-28 14:47:46" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211963786_0_0_801" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "li939icso9uujt1lmp3g9kcku0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "540.277 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.924 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1595926291000" -context "sdk\\\\hardware/1595926291000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1595926291000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1595926291000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1595926291000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1595926291000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1595926291000"
webtalk_add_data -client sdk -key Device -value "7z030" -context "sdk\\\\hardware/1595926291000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1595926291000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1595926291000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1595926291000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1595926291000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1595927866317"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1595927866317"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1595927866317"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1595927866317"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1595927866317"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1595927866317"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1595927866317"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1595927866317"
webtalk_transmit -clientid 3284423015 -regid "211963786_0_0_801" -xml /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
