# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/src/constraints/pzfmc-7z015-7z030-1v8.xdc

# XDC: /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/src/constraints/rgmii-0123.xdc

# Block Designs: bd/pz_7z030_axieth/pz_7z030_axieth.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth || ORIG_REF_NAME==pz_7z030_axieth} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_processing_system7_0_0/pz_7z030_axieth_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_processing_system7_0_0 || ORIG_REF_NAME==pz_7z030_axieth_processing_system7_0_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_rst_ps7_0_50M_0/pz_7z030_axieth_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_rst_ps7_0_50M_0 || ORIG_REF_NAME==pz_7z030_axieth_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_clk_wiz_0_0/pz_7z030_axieth_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_clk_wiz_0_0 || ORIG_REF_NAME==pz_7z030_axieth_clk_wiz_0_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_rst_clk_wiz_0_125M_0/pz_7z030_axieth_rst_clk_wiz_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_rst_clk_wiz_0_125M_0 || ORIG_REF_NAME==pz_7z030_axieth_rst_clk_wiz_0_125M_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_xlconcat_0_0/pz_7z030_axieth_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_xlconcat_0_0 || ORIG_REF_NAME==pz_7z030_axieth_xlconcat_0_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/pz_7z030_axieth_axi_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_axi_ethernet_0_0 || ORIG_REF_NAME==pz_7z030_axieth_axi_ethernet_0_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/pz_7z030_axieth_axi_ethernet_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_axi_ethernet_1_0 || ORIG_REF_NAME==pz_7z030_axieth_axi_ethernet_1_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/pz_7z030_axieth_axi_ethernet_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_axi_ethernet_2_0 || ORIG_REF_NAME==pz_7z030_axieth_axi_ethernet_2_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/pz_7z030_axieth_axi_ethernet_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_axi_ethernet_3_0 || ORIG_REF_NAME==pz_7z030_axieth_axi_ethernet_3_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_dma_0/pz_7z030_axieth_axi_ethernet_0_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_axi_ethernet_0_dma_0 || ORIG_REF_NAME==pz_7z030_axieth_axi_ethernet_0_dma_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_dma_0/pz_7z030_axieth_axi_ethernet_1_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_axi_ethernet_1_dma_0 || ORIG_REF_NAME==pz_7z030_axieth_axi_ethernet_1_dma_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_dma_0/pz_7z030_axieth_axi_ethernet_2_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_axi_ethernet_2_dma_0 || ORIG_REF_NAME==pz_7z030_axieth_axi_ethernet_2_dma_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_dma_0/pz_7z030_axieth_axi_ethernet_3_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_axi_ethernet_3_dma_0 || ORIG_REF_NAME==pz_7z030_axieth_axi_ethernet_3_dma_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_ps7_0_axi_periph_0/pz_7z030_axieth_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_ps7_0_axi_periph_0 || ORIG_REF_NAME==pz_7z030_axieth_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_mem_intercon_0/pz_7z030_axieth_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_axi_mem_intercon_0 || ORIG_REF_NAME==pz_7z030_axieth_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_ref_clk_oe_0/pz_7z030_axieth_ref_clk_oe_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_ref_clk_oe_0 || ORIG_REF_NAME==pz_7z030_axieth_ref_clk_oe_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_ref_clk_fsel_0/pz_7z030_axieth_ref_clk_fsel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_ref_clk_fsel_0 || ORIG_REF_NAME==pz_7z030_axieth_ref_clk_fsel_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_xbar_1/pz_7z030_axieth_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_xbar_1 || ORIG_REF_NAME==pz_7z030_axieth_xbar_1} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_xbar_0/pz_7z030_axieth_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_xbar_0 || ORIG_REF_NAME==pz_7z030_axieth_xbar_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_pc_1/pz_7z030_axieth_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_pc_1 || ORIG_REF_NAME==pz_7z030_axieth_auto_pc_1} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_11/pz_7z030_axieth_auto_us_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_us_11 || ORIG_REF_NAME==pz_7z030_axieth_auto_us_11} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_11/pz_7z030_axieth_auto_cc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_cc_11 || ORIG_REF_NAME==pz_7z030_axieth_auto_cc_11} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_10/pz_7z030_axieth_auto_us_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_us_10 || ORIG_REF_NAME==pz_7z030_axieth_auto_us_10} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_10/pz_7z030_axieth_auto_cc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_cc_10 || ORIG_REF_NAME==pz_7z030_axieth_auto_cc_10} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_9/pz_7z030_axieth_auto_us_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_us_9 || ORIG_REF_NAME==pz_7z030_axieth_auto_us_9} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_9/pz_7z030_axieth_auto_cc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_cc_9 || ORIG_REF_NAME==pz_7z030_axieth_auto_cc_9} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_8/pz_7z030_axieth_auto_us_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_us_8 || ORIG_REF_NAME==pz_7z030_axieth_auto_us_8} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_8/pz_7z030_axieth_auto_cc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_cc_8 || ORIG_REF_NAME==pz_7z030_axieth_auto_cc_8} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_7/pz_7z030_axieth_auto_us_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_us_7 || ORIG_REF_NAME==pz_7z030_axieth_auto_us_7} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_7/pz_7z030_axieth_auto_cc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_cc_7 || ORIG_REF_NAME==pz_7z030_axieth_auto_cc_7} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_6/pz_7z030_axieth_auto_us_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_us_6 || ORIG_REF_NAME==pz_7z030_axieth_auto_us_6} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_6/pz_7z030_axieth_auto_cc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_cc_6 || ORIG_REF_NAME==pz_7z030_axieth_auto_cc_6} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_5/pz_7z030_axieth_auto_us_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_us_5 || ORIG_REF_NAME==pz_7z030_axieth_auto_us_5} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_5/pz_7z030_axieth_auto_cc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_cc_5 || ORIG_REF_NAME==pz_7z030_axieth_auto_cc_5} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_4/pz_7z030_axieth_auto_us_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_us_4 || ORIG_REF_NAME==pz_7z030_axieth_auto_us_4} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_4/pz_7z030_axieth_auto_cc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_cc_4 || ORIG_REF_NAME==pz_7z030_axieth_auto_cc_4} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_3/pz_7z030_axieth_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_us_3 || ORIG_REF_NAME==pz_7z030_axieth_auto_us_3} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_3/pz_7z030_axieth_auto_cc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_cc_3 || ORIG_REF_NAME==pz_7z030_axieth_auto_cc_3} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_2/pz_7z030_axieth_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_us_2 || ORIG_REF_NAME==pz_7z030_axieth_auto_us_2} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_2/pz_7z030_axieth_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_cc_2 || ORIG_REF_NAME==pz_7z030_axieth_auto_cc_2} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_1/pz_7z030_axieth_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_us_1 || ORIG_REF_NAME==pz_7z030_axieth_auto_us_1} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_1/pz_7z030_axieth_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_cc_1 || ORIG_REF_NAME==pz_7z030_axieth_auto_cc_1} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_0/pz_7z030_axieth_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_us_0 || ORIG_REF_NAME==pz_7z030_axieth_auto_us_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_0/pz_7z030_axieth_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_cc_0 || ORIG_REF_NAME==pz_7z030_axieth_auto_cc_0} -quiet] -quiet

# IP: bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_pc_0/pz_7z030_axieth_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pz_7z030_axieth_auto_pc_0 || ORIG_REF_NAME==pz_7z030_axieth_auto_pc_0} -quiet] -quiet

# XDC: bd/pz_7z030_axieth/pz_7z030_axieth_ooc.xdc
