# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z030sbg485-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.cache/wt [current_project]
set_property parent.project_path /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:picozed_7030_fmc2:part0:1.1 [current_project]
set_property ip_output_repo /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/hdl/pz_7z030_axieth_wrapper.v
add_files /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/pz_7z030_axieth.bd
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_processing_system7_0_0/pz_7z030_axieth_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_rst_ps7_0_50M_0/pz_7z030_axieth_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_rst_ps7_0_50M_0/pz_7z030_axieth_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_rst_ps7_0_50M_0/pz_7z030_axieth_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_clk_wiz_0_0/pz_7z030_axieth_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_clk_wiz_0_0/pz_7z030_axieth_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_clk_wiz_0_0/pz_7z030_axieth_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_rst_clk_wiz_0_125M_0/pz_7z030_axieth_rst_clk_wiz_0_125M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_rst_clk_wiz_0_125M_0/pz_7z030_axieth_rst_clk_wiz_0_125M_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_rst_clk_wiz_0_125M_0/pz_7z030_axieth_rst_clk_wiz_0_125M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/bd_0/ip/ip_0/bd_1f27_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_1f27_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/bd_0/ip/ip_0/bd_1f27_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1f27_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1f27_mac_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1f27_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1f27_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/bd_0/ip/ip_2/bd_1f27_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/bd_0/ip/ip_3/bd_1f27_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/bd_0/bd_1f27_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/pz_7z030_axieth_axi_ethernet_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_0/synth/pz_7z030_axieth_axi_ethernet_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/bd_0/ip/ip_0/bd_df76_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/bd_0/ip/ip_0/synth/bd_df76_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/bd_0/ip/ip_0/bd_df76_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_df76_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_df76_mac_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_df76_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_df76_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/bd_0/ip/ip_2/bd_df76_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/bd_0/ip/ip_3/bd_df76_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/bd_0/bd_df76_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/pz_7z030_axieth_axi_ethernet_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_0/synth/pz_7z030_axieth_axi_ethernet_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/bd_0/ip/ip_0/bd_df86_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/bd_0/ip/ip_0/synth/bd_df86_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/bd_0/ip/ip_0/bd_df86_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/bd_0/ip/ip_1/synth/bd_df86_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/bd_0/ip/ip_1/synth/bd_df86_mac_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/bd_0/ip/ip_1/synth/bd_df86_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/bd_0/ip/ip_1/synth/bd_df86_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/bd_0/ip/ip_2/bd_df86_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/bd_0/ip/ip_3/bd_df86_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/bd_0/bd_df86_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/pz_7z030_axieth_axi_ethernet_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_0/synth/pz_7z030_axieth_axi_ethernet_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_0/bd_1fd7_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_0/synth/bd_1fd7_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_0/bd_1fd7_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_1/synth/bd_1fd7_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_1/synth/bd_1fd7_mac_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_1/synth/bd_1fd7_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_1/synth/bd_1fd7_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_2/bd_1fd7_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/ip/ip_3/bd_1fd7_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/bd_0/bd_1fd7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/pz_7z030_axieth_axi_ethernet_3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_0/synth/pz_7z030_axieth_axi_ethernet_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_dma_0/pz_7z030_axieth_axi_ethernet_0_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_dma_0/pz_7z030_axieth_axi_ethernet_0_dma_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_0_dma_0/pz_7z030_axieth_axi_ethernet_0_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_dma_0/pz_7z030_axieth_axi_ethernet_1_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_dma_0/pz_7z030_axieth_axi_ethernet_1_dma_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_1_dma_0/pz_7z030_axieth_axi_ethernet_1_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_dma_0/pz_7z030_axieth_axi_ethernet_2_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_dma_0/pz_7z030_axieth_axi_ethernet_2_dma_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_2_dma_0/pz_7z030_axieth_axi_ethernet_2_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_dma_0/pz_7z030_axieth_axi_ethernet_3_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_dma_0/pz_7z030_axieth_axi_ethernet_3_dma_0.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_axi_ethernet_3_dma_0/pz_7z030_axieth_axi_ethernet_3_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_xbar_1/pz_7z030_axieth_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_xbar_0/pz_7z030_axieth_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_pc_1/pz_7z030_axieth_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_11/pz_7z030_axieth_auto_us_11_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_11/pz_7z030_axieth_auto_us_11_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_11/pz_7z030_axieth_auto_us_11_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_11/pz_7z030_axieth_auto_cc_11_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_11/pz_7z030_axieth_auto_cc_11_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_11/pz_7z030_axieth_auto_cc_11_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_10/pz_7z030_axieth_auto_us_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_10/pz_7z030_axieth_auto_us_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_10/pz_7z030_axieth_auto_us_10_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_10/pz_7z030_axieth_auto_cc_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_10/pz_7z030_axieth_auto_cc_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_10/pz_7z030_axieth_auto_cc_10_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_9/pz_7z030_axieth_auto_us_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_9/pz_7z030_axieth_auto_us_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_9/pz_7z030_axieth_auto_us_9_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_9/pz_7z030_axieth_auto_cc_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_9/pz_7z030_axieth_auto_cc_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_9/pz_7z030_axieth_auto_cc_9_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_8/pz_7z030_axieth_auto_us_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_8/pz_7z030_axieth_auto_us_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_8/pz_7z030_axieth_auto_us_8_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_8/pz_7z030_axieth_auto_cc_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_8/pz_7z030_axieth_auto_cc_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_8/pz_7z030_axieth_auto_cc_8_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_7/pz_7z030_axieth_auto_us_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_7/pz_7z030_axieth_auto_us_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_7/pz_7z030_axieth_auto_us_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_7/pz_7z030_axieth_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_7/pz_7z030_axieth_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_7/pz_7z030_axieth_auto_cc_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_6/pz_7z030_axieth_auto_us_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_6/pz_7z030_axieth_auto_us_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_6/pz_7z030_axieth_auto_us_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_6/pz_7z030_axieth_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_6/pz_7z030_axieth_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_6/pz_7z030_axieth_auto_cc_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_5/pz_7z030_axieth_auto_us_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_5/pz_7z030_axieth_auto_us_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_5/pz_7z030_axieth_auto_us_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_5/pz_7z030_axieth_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_5/pz_7z030_axieth_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_5/pz_7z030_axieth_auto_cc_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_4/pz_7z030_axieth_auto_us_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_4/pz_7z030_axieth_auto_us_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_4/pz_7z030_axieth_auto_us_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_4/pz_7z030_axieth_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_4/pz_7z030_axieth_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_4/pz_7z030_axieth_auto_cc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_3/pz_7z030_axieth_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_3/pz_7z030_axieth_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_3/pz_7z030_axieth_auto_us_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_3/pz_7z030_axieth_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_3/pz_7z030_axieth_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_3/pz_7z030_axieth_auto_cc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_2/pz_7z030_axieth_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_2/pz_7z030_axieth_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_2/pz_7z030_axieth_auto_us_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_2/pz_7z030_axieth_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_2/pz_7z030_axieth_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_2/pz_7z030_axieth_auto_cc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_1/pz_7z030_axieth_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_1/pz_7z030_axieth_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_1/pz_7z030_axieth_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_1/pz_7z030_axieth_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_1/pz_7z030_axieth_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_1/pz_7z030_axieth_auto_cc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_0/pz_7z030_axieth_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_0/pz_7z030_axieth_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_us_0/pz_7z030_axieth_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_0/pz_7z030_axieth_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_0/pz_7z030_axieth_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_cc_0/pz_7z030_axieth_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/ip/pz_7z030_axieth_auto_pc_0/pz_7z030_axieth_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/pz_7z030_axieth/pz_7z030_axieth.srcs/sources_1/bd/pz_7z030_axieth/pz_7z030_axieth_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/src/constraints/pzfmc-7z015-7z030-1v8.xdc
set_property used_in_implementation false [get_files /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/src/constraints/pzfmc-7z015-7z030-1v8.xdc]

read_xdc /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/src/constraints/rgmii-0123.xdc
set_property used_in_implementation false [get_files /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/src/constraints/rgmii-0123.xdc]
set_property processing_order LATE [get_files /home/shreyas/Desktop/projects/picozedFMCeth/Vivado/src/constraints/rgmii-0123.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top pz_7z030_axieth_wrapper -part xc7z030sbg485-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pz_7z030_axieth_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pz_7z030_axieth_wrapper_utilization_synth.rpt -pb pz_7z030_axieth_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
